name: Upload Release
on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  checkout:
    name: Upload to Release - No NodeJS
    runs-on: ubuntu-latest
    steps:
      - name: Dummy Files
        run: |
          echo 'fo binary' > fo-vx.y.z.xbps
          echo 'fo signature' > fo-vx.y.z.sig2
      - name: Checkout
        uses: void-musl/upload-release@v1.0.2
        with:
          tag: 'build-${{ github.run_number }}'
          rel_name: 'fo build'
          file_pat: '*.xbps *.sig2'
          gh_token: ${{ secrets.GITHUB_TOKEN }}
